# Generated by Django 3.0.5 on 2020-06-01 20:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerV_name', models.CharField(max_length=50)),
                ('SerV_birth_date', models.DateField(null=True)),
                ('SerV_age', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(80)])),
                ('SerV_address', models.CharField(default='', max_length=255)),
                ('SerV_phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('SerV_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('TransGen', 'TransGen')], default='Male', max_length=10)),
                ('SerV_Profile_pick', models.ImageField(blank=True, null=True, upload_to='SerVProfile/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(12)])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='I use this app to help others...', max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('TransGen', 'TransGen')], default='Male', max_length=10)),
                ('profile_pick', models.ImageField(blank=True, null=True, upload_to='Profile/images')),
                ('profile_Background_pic', models.ImageField(blank=True, null=True, upload_to='Profile/background_Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pick', models.ImageField(null=True, upload_to='UsrPost/post_img')),
                ('subject', models.CharField(max_length=75)),
                ('msg', models.TextField(blank=True, null=True)),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('uploded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.NormalProfile')),
            ],
        ),
        migrations.CreateModel(
            name='NormalPostComment',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_by', to='Account.NormalProfile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.NormalPostComment')),
                ('post_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_is', to='Account.NormalPosts')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ManyToManyField(related_name='NormalPost_Like_by', to=settings.AUTH_USER_MODEL)),
                ('normal_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.NormalPosts')),
            ],
        ),
        migrations.CreateModel(
            name='FollowersFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.ManyToManyField(related_name='following', to='Account.NormalProfile')),
                ('following_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.NormalProfile')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisB_name', models.CharField(max_length=50)),
                ('DisB_birth_date', models.DateField(null=True)),
                ('DisB_age', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(80)])),
                ('DisB_address', models.CharField(default='', max_length=255)),
                ('DisB_phone_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
                ('DisB_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('TransGen', 'TransGen')], default='Male', max_length=10)),
                ('DisB_Profile_pick', models.ImageField(blank=True, null=True, upload_to='DisB_Profile_pick/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatWithFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_txt', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
