# Generated by Django 3.0.5 on 2020-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatwithfriends',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='chatwithfriends',
            name='msg_txt',
            field=models.TextField(max_length=255),
        ),
    ]
