# Generated by Django 3.0.5 on 2020-06-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200603_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatwithfriends',
            options={'ordering': ('timestamp',)},
        ),
    ]
