# Generated by Django 3.0.5 on 2020-06-13 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CapMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='pop_up_text',
            field=models.CharField(default=datetime.datetime(2020, 6, 13, 12, 2, 39, 903093, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
    ]
