# Generated by Django 3.0.5 on 2020-06-11 06:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.NormalProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_picture', models.ImageField(upload_to='products/images')),
                ('prod_price', models.FloatField(default=0, max_length=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('in_terms_of', models.CharField(choices=[('pack', 'pack'), ('piece', 'piece'), ('kg', 'kg'), ('gm', 'gm'), ('L', 'L'), ('ml', 'ml')], default='Male', max_length=10)),
                ('prod_description', models.TextField()),
                ('prod_offer', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('prod_upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.ServiceProviderProfile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('in_terms_of', models.IntegerField(choices=[(1, '/pack'), (2, '/piece'), (3, '/kg'), (4, '/gm'), (5, '/L'), (6, '/ml')], default=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShopHome.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShopHome.Products')),
            ],
        ),
    ]
